spring:
  mail:
    username: 972042778@qq.com
    password:  #qq提供的
    host: smtp.qq.com #\u5728qq\u91CC\u9762\u67E5\u770B
#    properties:
#      mail:
#          smtp:
#            auth: true  # \u9700\u8981\u9A8C\u8BC1\u767B\u5F55\u540D\u548C\u5BC6\u7801
#          starttls:
#            enable: true  # \u9700\u8981TLS\u8BA4\u8BC1 \u4FDD\u8BC1\u53D1\u9001\u90AE\u4EF6\u5B89\u5168\u9A8C\u8BC1
#            required: true